CADC-10640: cadc-vos-server and cadc-test-vos, cavern using cadc-vos 2.0
opencadc/vos pull request #115
Opened 2022-01-12 20:52 UTC by hjeeves

…o new Transfer.java in cadc-vos 2.0

2022-01-13 22:01 UTC, brianmajor requested changes
It's true that BiDirectionalTransferNegotiation will never support zip/tar -- it represents an open cavern mount I believe.

PushToVoSpaceTransferNegotiation is an upload so it's correct that multiple targets are not supported there.

PullFromVoSpaceTransferNegotiation will however be represented in new transfer docs with multiple targets.  So perhaps you comments that are in TransferNegotiation.java below in PullFromVoSpaceTransferNegotiation?

I'm not sure if the code in PullFromVoSpaceTransferNegotiation will actually be execute when view=zip/tar.  It could be that the view makes TransferRunner skip some of these steps.  TBD.

2022-01-14 00:03 UTC, hjeeves commented on cadc-test-vos/src/main/java/ca/nrc/cadc/conformance/vos/AsyncPullFromVOSpaceTest.java
> +            transfer.setView(view);
It must not have picked up cadc-vos 2.0.  That ctor doesn't exist anymore.

2022-01-14 17:57 UTC, hjeeves commented on cadc-vos-server/src/main/java/ca/nrc/cadc/vos/server/transfers/TransferUtil.java
> +    public static void confirmSingleTarget(Transfer transfer) throws TransferException {
It's used in PushFromVOSpaceNegotiation, PullFromVOSpaceNegotiation and BiDirectionalTransfer.

2022-01-14 17:59 UTC, hjeeves commented on cadc-vos-server/src/main/java/ca/nrc/cadc/vos/server/transfers/TransferRunner.java
>              catch (NodeNotFoundException ignore)
done.

2022-01-14 17:59 UTC, hjeeves commented on cadc-vos-server/src/main/java/ca/nrc/cadc/vos/server/transfers/TransferRunner.java
> +                VOSURI vosURI = new VOSURI(transfer.getTargets().get(0));
removed, made this log.debug statement similar to the ones in the other catch stanzas.

2022-01-14 18:00 UTC, hjeeves commented on cadc-vos-server/src/main/java/ca/nrc/cadc/vos/server/transfers/TransferDetailsServlet.java
> +                        // This is save for now because of the check above (CADC-10640)
done

2022-01-14 18:00 UTC, hjeeves commented on cadc-vos-server/build.gradle
> +version = '1.2.4'
changed to 1.3

2022-01-14 18:00 UTC, hjeeves commented on cadc-test-vos/build.gradle
done

2022-01-14 18:09 UTC, brianmajor approved these changes

2022-01-14 22:05 UTC, brianmajor requested changes
Null pointer in TransferReader must be fixed first.  Seen when running the cavern int tests.

```	
java.lang.NullPointerException
at java.util.ArrayList.addAll(ArrayList.java:581)
at ca.nrc.cadc.vos.TransferReader.parseTransfer(TransferReader.java:213)
at ca.nrc.cadc.vos.TransferReader.read(TransferReader.java:146)
at ca.nrc.cadc.vos.TransferReader.read(TransferReader.java:157)
at ca.nrc.cadc.vos.server.TransferInlineContentHandler.accept(TransferInlineContentHandler.java:120)
	```

2022-01-14 22:56 UTC, brianmajor approved these changes
cavern int-tests now passing with the update

2022-01-14 23:07 UTC, merged