CADC-11650, 11671, 11672 - adding cavern/preauth and new access to cavern/files
opencadc/vos pull request #128
Opened 2022-08-08 20:06 UTC by hjeeves

cavern/files is not supported beyond the URL (no authentication or actual files returned, just an unsupported message.) cavern/preauth endpoint maintains existing preauth behaviour. Integration tests run fully.

2022-08-09 17:11 UTC, brianmajor requested changes

2022-08-09 17:11 UTC, brianmajor commented on cavern/src/main/java/org/opencadc/cavern/files/CavernURLGenerator.java
> +        VOSURI targetVOSURI = new VOSURI(targetURI);
There is a constructor for VOSURI that takes a String.  That should remove some of the complication in this method.

2022-08-09 17:11 UTC, brianmajor commented on cavern/src/main/webapp/capabilities.xml
> +</vosi:capabilities>
Hard to tell what changed in this file as it says the whole thing changed...

2022-08-09 17:11 UTC, brianmajor commented on cavern/src/main/webapp/WEB-INF/web.xml
> +      <param-value>true</param-value>
I would use different classes (that respond to different endpoints /preauth and /files) rather than in here.

2022-08-09 17:12 UTC, brianmajor commented
Seems like trying to use a single class to do everything has gotten messy.  Do Puts to Files (non preauth) work now as part of this work?

2022-08-12 22:43 UTC, hjeeves commented
Closing this as reverting code (because the QuotaTest int tests were failing for a reason that was too complex to debug, so the last code changes in this branch were redone in another branch.

2022-08-12 22:43 UTC, closed without merging