CADC-11395 Added recursive set node feature to cavern.
opencadc/vos pull request #143
Opened 2023-02-02 21:37 UTC by yeunga

2023-02-11 01:44 UTC, hjeeves requested changes
Really minor things about date stamps on headers and commented code. :) Otherwise looks good.

2023-02-13 17:52 UTC, yeunga commented on cavern/src/intTest/java/org/opencadc/cavern/RecursiveSetNodeRunnerTest.java
> +*  (c) 2011.                            (c) 2011.
Updated

2023-02-13 17:53 UTC, yeunga commented on cavern/src/intTest/java/org/opencadc/cavern/RecursiveSetNodeRunnerTest.java
> +//        DataNode data = new DataNode(new VOSURI(new URI(nodeURI + "/dataNode")));
Removed.

2023-02-13 17:54 UTC, yeunga commented on cavern/src/main/java/org/opencadc/cavern/JobAbortedException.java
> + * @author majorb
Updated.

2023-02-13 17:58 UTC, yeunga commented on cavern/src/main/java/org/opencadc/cavern/RecursiveSetNodeJobManager.java
> +*  (c) 2009.                            (c) 2009.
Updated.

2023-02-13 17:59 UTC, yeunga commented on cavern/src/main/java/org/opencadc/cavern/RecursiveSetNodeJobManager.java
> + * @author pdowler, majorb
Added my name to the list.

2023-02-13 18:00 UTC, yeunga commented on cavern/src/main/java/org/opencadc/cavern/RecursiveSetNodeRunner.java
> +*  (c) 2009.                            (c) 2009.
Updated.

2023-02-13 18:00 UTC, yeunga commented on cavern/src/main/java/org/opencadc/cavern/RecursiveSetNodeRunner.java
> + * @author majorb
Added my name as an author.

2023-02-13 18:18 UTC, yeunga commented on cavern/src/main/java/org/opencadc/cavern/RecursiveSetNodeRunner.java
> +        log.info(startMessage);
I think timing statements are okay. Just following what vault is doing.

2023-02-13 18:24 UTC, yeunga commented on cavern/src/main/java/org/opencadc/cavern/RecursiveSetNodeRunner.java
> +                if (container.getNodes().size() == CHILD_BATCH_SIZE)
Corrected all braces.

2023-02-13 19:07 UTC, yeunga commented on cavern/src/main/java/org/opencadc/cavern/JobAbortedException.java
> +*  (c) 2009.                            (c) 2009.
Updated to 2023.

2023-02-13 19:15 UTC, yeunga commented
Looks like the threee check failures are the result of Pat's updates to A&A currently in progress.

2023-03-07 22:50 UTC, brianmajor approved these changes

2023-03-07 22:50 UTC, merged